// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: api/calculator/v1/calculator.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CalcBody *CalcReq_CalcBody `protobuf:"bytes,1,opt,name=calc_body,json=calcBody,proto3" json:"calc_body,omitempty"`
}

func (x *CalcReq) Reset() {
	*x = CalcReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_calculator_v1_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcReq) ProtoMessage() {}

func (x *CalcReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_v1_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcReq.ProtoReflect.Descriptor instead.
func (*CalcReq) Descriptor() ([]byte, []int) {
	return file_api_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalcReq) GetCalcBody() *CalcReq_CalcBody {
	if x != nil {
		return x.CalcBody
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Master int32 `protobuf:"varint,1,opt,name=master,proto3" json:"master,omitempty"`
	Slave  int32 `protobuf:"varint,2,opt,name=slave,proto3" json:"slave,omitempty"`
	Shun   int32 `protobuf:"varint,3,opt,name=shun,proto3" json:"shun,omitempty"`
	Ke     int32 `protobuf:"varint,4,opt,name=ke,proto3" json:"ke,omitempty"`
	Dui    int32 `protobuf:"varint,5,opt,name=dui,proto3" json:"dui,omitempty"`
	Ca     int32 `protobuf:"varint,6,opt,name=ca,proto3" json:"ca,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_calculator_v1_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_v1_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetMaster() int32 {
	if x != nil {
		return x.Master
	}
	return 0
}

func (x *Item) GetSlave() int32 {
	if x != nil {
		return x.Slave
	}
	return 0
}

func (x *Item) GetShun() int32 {
	if x != nil {
		return x.Shun
	}
	return 0
}

func (x *Item) GetKe() int32 {
	if x != nil {
		return x.Ke
	}
	return 0
}

func (x *Item) GetDui() int32 {
	if x != nil {
		return x.Dui
	}
	return 0
}

func (x *Item) GetCa() int32 {
	if x != nil {
		return x.Ca
	}
	return 0
}

type CalcRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conf  string `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	Desc1 string `protobuf:"bytes,2,opt,name=desc1,proto3" json:"desc1,omitempty"`
	Desc2 string `protobuf:"bytes,3,opt,name=desc2,proto3" json:"desc2,omitempty"`
	Desc3 string `protobuf:"bytes,4,opt,name=desc3,proto3" json:"desc3,omitempty"`
	Desc4 string `protobuf:"bytes,5,opt,name=desc4,proto3" json:"desc4,omitempty"`
}

func (x *CalcRsp) Reset() {
	*x = CalcRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_calculator_v1_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRsp) ProtoMessage() {}

func (x *CalcRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_v1_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRsp.ProtoReflect.Descriptor instead.
func (*CalcRsp) Descriptor() ([]byte, []int) {
	return file_api_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalcRsp) GetConf() string {
	if x != nil {
		return x.Conf
	}
	return ""
}

func (x *CalcRsp) GetDesc1() string {
	if x != nil {
		return x.Desc1
	}
	return ""
}

func (x *CalcRsp) GetDesc2() string {
	if x != nil {
		return x.Desc2
	}
	return ""
}

func (x *CalcRsp) GetDesc3() string {
	if x != nil {
		return x.Desc3
	}
	return ""
}

func (x *CalcRsp) GetDesc4() string {
	if x != nil {
		return x.Desc4
	}
	return ""
}

type CalcReq_CalcBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Close    bool    `protobuf:"varint,1,opt,name=close,proto3" json:"close,omitempty"`       //是否关闭
	Kind     int32   `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`         //1，2
	Continue bool    `protobuf:"varint,3,opt,name=continue,proto3" json:"continue,omitempty"` //是否连牌
	Items    []*Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`        //配置
}

func (x *CalcReq_CalcBody) Reset() {
	*x = CalcReq_CalcBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_calculator_v1_calculator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcReq_CalcBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcReq_CalcBody) ProtoMessage() {}

func (x *CalcReq_CalcBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_calculator_v1_calculator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcReq_CalcBody.ProtoReflect.Descriptor instead.
func (*CalcReq_CalcBody) Descriptor() ([]byte, []int) {
	return file_api_calculator_v1_calculator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CalcReq_CalcBody) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *CalcReq_CalcBody) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *CalcReq_CalcBody) GetContinue() bool {
	if x != nil {
		return x.Continue
	}
	return false
}

func (x *CalcReq_CalcBody) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_calculator_v1_calculator_proto protoreflect.FileDescriptor

var file_api_calculator_v1_calculator_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65,
	0x71, 0x12, 0x40, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71,
	0x2e, 0x43, 0x61, 0x6c, 0x63, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x63, 0x42,
	0x6f, 0x64, 0x79, 0x1a, 0x7f, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x63, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x7a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68,
	0x75, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x68, 0x75, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x6b, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6b, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x75, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x75, 0x69,
	0x12, 0x0e, 0x0a, 0x02, 0x63, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63, 0x61,
	0x22, 0x75, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x63, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x65, 0x73, 0x63, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x63, 0x32, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x73, 0x63, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x73, 0x63, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x73, 0x63,
	0x33, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x63, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x65, 0x73, 0x63, 0x34, 0x32, 0x62, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x54, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x52, 0x73, 0x70, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x3a, 0x01, 0x2a, 0x42, 0x36, 0x0a, 0x11, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x1f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_api_calculator_v1_calculator_proto_rawDescData = file_api_calculator_v1_calculator_proto_rawDesc
)

func file_api_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_api_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_api_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_calculator_v1_calculator_proto_rawDescData)
	})
	return file_api_calculator_v1_calculator_proto_rawDescData
}

var file_api_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_calculator_v1_calculator_proto_goTypes = []interface{}{
	(*CalcReq)(nil),          // 0: api.calculator.v1.CalcReq
	(*Item)(nil),             // 1: api.calculator.v1.Item
	(*CalcRsp)(nil),          // 2: api.calculator.v1.CalcRsp
	(*CalcReq_CalcBody)(nil), // 3: api.calculator.v1.CalcReq.CalcBody
}
var file_api_calculator_v1_calculator_proto_depIdxs = []int32{
	3, // 0: api.calculator.v1.CalcReq.calc_body:type_name -> api.calculator.v1.CalcReq.CalcBody
	1, // 1: api.calculator.v1.CalcReq.CalcBody.items:type_name -> api.calculator.v1.Item
	0, // 2: api.calculator.v1.Calculator.Calc:input_type -> api.calculator.v1.CalcReq
	2, // 3: api.calculator.v1.Calculator.Calc:output_type -> api.calculator.v1.CalcRsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_calculator_v1_calculator_proto_init() }
func file_api_calculator_v1_calculator_proto_init() {
	if File_api_calculator_v1_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_calculator_v1_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_calculator_v1_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_calculator_v1_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_calculator_v1_calculator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcReq_CalcBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_calculator_v1_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_api_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_api_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_api_calculator_v1_calculator_proto = out.File
	file_api_calculator_v1_calculator_proto_rawDesc = nil
	file_api_calculator_v1_calculator_proto_goTypes = nil
	file_api_calculator_v1_calculator_proto_depIdxs = nil
}
