// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type CalculatorHTTPServer interface {
	Calc(context.Context, *CalcReq) (*CalcRsp, error)
}

func RegisterCalculatorHTTPServer(s *http.Server, srv CalculatorHTTPServer) {
	r := s.Route("/")
	r.POST("/api/calc", _Calculator_Calc0_HTTP_Handler(srv))
}

func _Calculator_Calc0_HTTP_Handler(srv CalculatorHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CalcReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.calculator.v1.Calculator/Calc")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Calc(ctx, req.(*CalcReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CalcRsp)
		return ctx.Result(200, reply)
	}
}

type CalculatorHTTPClient interface {
	Calc(ctx context.Context, req *CalcReq, opts ...http.CallOption) (rsp *CalcRsp, err error)
}

type CalculatorHTTPClientImpl struct {
	cc *http.Client
}

func NewCalculatorHTTPClient(client *http.Client) CalculatorHTTPClient {
	return &CalculatorHTTPClientImpl{client}
}

func (c *CalculatorHTTPClientImpl) Calc(ctx context.Context, in *CalcReq, opts ...http.CallOption) (*CalcRsp, error) {
	var out CalcRsp
	pattern := "/api/calc"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.calculator.v1.Calculator/Calc"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
