// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"calculator/internal/biz"
	"calculator/internal/conf"
	"calculator/internal/data"
	"calculator/internal/server"
	"calculator/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	calculatorRepo := data.NewCalculatorRepo(dataData, logger)
	calculatorUseCase := biz.NewCalculatorUseCase(calculatorRepo, logger)
	calculatorService := service.NewCalculatorService(calculatorUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, calculatorService, logger)
	grpcServer := server.NewGRPCServer(confServer, calculatorService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
