// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"mytest/internal/biz"
	"mytest/internal/conf"
	"mytest/internal/data"
	"mytest/internal/server"
	"mytest/internal/service"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	producer, err := data.NewKafka(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db, client, producer)
	if err != nil {
		return nil, nil, err
	}
	useRepo := data.NewUseRepo(dataData)
	useCase := biz.NewUsecase(useRepo)
	serviceService := service.NewGreeterService(useCase)
	engine := server.NewHTTPServer(confServer, serviceService)
	grpcServer := server.NewGrpcServer(confServer, serviceService)
	app := newApp(engine, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
